##################################################
# Playbooks: LEMP on Ubuntu 20.04
##################################################
---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Install LEMP Packages
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'nginx', 'mysql-server', 'python3-pymysql', 'php-fpm', 'php-mysql' ]
    
# Nginx Configuration
    - name: Sets Nginx conf file
      template:
        src: "files/nginx.conf.j2"
        dest: "/etc/nginx/sites-available/{{ http_conf }}"

    - name: Enables new site
      file:
        src: "/etc/nginx/sites-available/{{ http_conf }}"
        dest: "/etc/nginx/sites-enabled/{{ http_conf }}"
        state: link
      notify: Reload Nginx
    
    - name: Removes "default" site
      file:
        path: "/etc/nginx/sites-enabled/default"
        state: absent
      notify: Reload Nginx

# Thay doi password MySQL
    - name: Thay doi password root MySQL
      shell: |
        temp_password=$(grep password /var/log/mysqld.log | awk '{print $NF}' | head -n1)
        echo "ALTER USER 'root'@'localhost' IDENTIFIED BY '123'; flush privileges;" > reset_pass.sql
        mysql -u root --password=$temp_password --connect-expired-password < reset_pass.sql

#    - name: Removes all anonymous user accounts
#      mysql_user:
#        name: ''
#        host_all: yes
#        state: absent
#        login_user: root
#        login_password: "{{ mysql_root_password }}"

#    - name: Removes the MySQL test database
#      mysql_db: 
#        name: test 
#        state: absent
#        login_user: root
#        login_password: "{{ mysql_root_password }}"

# UFW Configuration
    - name: "UFW - Allow HTTP on port {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp

# Sets Up PHP Info Page
    - name: Sets Up PHP Info Page
      template:
        src: "files/info.php.j2"
        dest: "/var/www/html/info.php"

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
